### PR TITLE
[#60][#62] Unchecked Exception in Parser

### LINKED ISSUE #60: Uncaught Exception in Parser
The parser fails to throw the ParseException when the parser expects the input to be of the float number type AND the input not being a valid number. This can lead to uncaught exceptions by unexpected input, which may lead to Denial-of-Service (DoS).

https://github.com/netplex/json-smart-v2/blob/4402bae12ada8009502b3da5b0d76a2bdac86cec/json-smart/src/main/java/net/minidev/json/parser/JSONParserBase.java#L139-L147

Parser Input of "-." or "2e+" or "[45e-" will crash with a NumberFormatException.

```
== Java Exception: java.lang.NumberFormatException: For input string: "-."
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:549)
	at net.minidev.json.parser.JSONParserBase.extractFloat(JSONParserBase.java:141)
```

### PR DESCRIPTION
**Pull request by dpeger**
- Applied fix for uncaught unchecked `NumberFormatException` in `JSONParserBase` (Fixes #60 , #62)
- Updated maven poms
- Updated version to 2.3.1

### CODE REVIEW

**Review by UrielCh — APPROVED** [review]

**Comment by UrielCh** [comment]
Looks good, except that you include [PR74](https://github.com/netplex/json-smart-v2/pull/74), this PR in not published in any V2.4 version yet.

**Comment by dpeger** [comment]
Do you want me to backout the fix for #73 from this PR and create a dedicated PR for this for v2.3 branch? Or do you simply want to wait until PR #74 was released for v.2.4?

**Comment by UrielCh** [comment]
PR74 should not be included in branch 2.3; it could cause breathing changes for current users; the parser is now based on OS environment default encoding.

Maybe I'm wrong.

**Comment by dpeger** [comment]
I reverted the fix for #73 as this might introduce a breaking change.

**Comment by dpeger** [comment]
@UrielCh would you mind to have a second look an merge this PR? I was hoping to see the fixed version in the next spring-boot update...

**Pull request merged**
