### PR TITLE
configure Reproducible Builds

### PR DESCRIPTION
**Pull request by hboutemy**
see https://maven.apache.org/guides/mini/guide-reproducible-builds.html

### CODE REVIEW

**Comment by Shoothzj** [comment]
@hboutemy Hi, thanks for your contribution, could you please modify file `json-smart-action/pom.xml` too? Thanks

**Comment by darxriggs** [comment]
@hboutemy gentle reminder

**Comment by hboutemy** [comment]
other pom.xml modified as requested :)

**Review by Shoothzj — APPROVED** [review]

**Comment by Shoothzj** [comment]
@hboutemy Thanks for your contribution. :)

**Pull request merged**
